services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8000"  # Host port 8001 → container port 8000
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: project2_db
      POSTGRES_USER: project2_user
      POSTGRES_PASSWORD: project2_pass
    ports:
      - "5433:5432"  # Host port 5433 → container port 5432
    volumes:
      - project2_postgres_data:/var/lib/postgresql/data

volumes:
  project2_postgres_data:
